# DUG-Seis parameter file
#
# :copyright:
#    ETH Zurich, Switzerland
# :license:
#    GNU Lesser General Public License, Version 3
#    (https://www.gnu.org/copyleft/lesser.html)
#

Version                       : 1
General:
  project_name                : Bedretto_commissioning
  project_location            : Bedretto
  operator                    : ['L. Villiger']
  project_description         : comissioning phase
  acquisition_folder          : ./raw_waveforms

  stats:
    network                   : XB # trace naming

Acquisition:
  hardware_settings:
    # vertical_resolution       : 16 # bit
    wait_for_trigger          : true
    external_clock            : true
    sampling_frequency        : 200000
    input_range: [ 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
                   10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
                   10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000] # +/- mV input range
  asdf_settings:
    compression               : gzip-3
    file_length_sec           : 10.0

