# DUG-Seis parameter file
#
# :copyright:
#    ETH Zurich, Switzerland
# :license:
#    GNU Lesser General Public License, Version 3
#    (https://www.gnu.org/copyleft/lesser.html)
#

Version                       : 1
General:
  project_name                : Bedretto_commissioning
  project_location            : Bedretto
  operator                    : ['L. Villiger']
  project_description         : comissioning phase
  acquisition_folder          : ./01_dummy_Grimsel/01_ASDF_data  # / recommended

  stats:
    network                   : XB # trace naming
    daq_unit                  : 02 # 02 for continuous-2, 03 for continuous-3, 04 for continuous-4

Acquisition:
  hardware_settings:
    # vertical_resolution       : 16 # bit
    wait_for_trigger          : false
    external_clock            : false
    sampling_frequency        : 200000
    input_range: [ 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
                   10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
                   10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000] # +/- mV input range
  asdf_settings:
    compression               : gzip-3
    file_length_sec           : 6.0

